/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bl.CellRenderer;
import bl.tableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author oskar
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    private tableModel bl  = new tableModel();
    public GUI() {
        initComponents();
        
        table.setModel(bl);
        table.setDefaultRenderer(Object.class, new CellRenderer());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMAddNewArticle = new javax.swing.JMenuItem();
        jMRemoveSelectedArticle = new javax.swing.JMenuItem();
        jMEditSelectedArticle = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMBuySelectedJArticle = new javax.swing.JMenuItem();
        jMSellSelectedArticle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);

        jMenu1.setText("Managment");

        jMAddNewArticle.setText("Add New Article");
        jMAddNewArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAddNewArticleActionPerformed(evt);
            }
        });
        jMenu1.add(jMAddNewArticle);

        jMRemoveSelectedArticle.setText("Remove Selected Article");
        jMRemoveSelectedArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRemoveSelectedArticleActionPerformed(evt);
            }
        });
        jMenu1.add(jMRemoveSelectedArticle);

        jMEditSelectedArticle.setText("Edit Selected Article");
        jMEditSelectedArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEditSelectedArticleActionPerformed(evt);
            }
        });
        jMenu1.add(jMEditSelectedArticle);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buy / Sell");

        jMBuySelectedJArticle.setText("Buy Selected ARticle");
        jMBuySelectedJArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBuySelectedJArticleActionPerformed(evt);
            }
        });
        jMenu2.add(jMBuySelectedJArticle);

        jMSellSelectedArticle.setText("Sell Selected ARticle");
        jMSellSelectedArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSellSelectedArticleActionPerformed(evt);
            }
        });
        jMenu2.add(jMSellSelectedArticle);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMBuySelectedJArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBuySelectedJArticleActionPerformed
        try {
            bl.buyArticles(table.getSelectedRow(),Integer.parseInt(JOptionPane.showInputDialog("Please enter the amount of articles you want to buy")));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMBuySelectedJArticleActionPerformed

    private void jMAddNewArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAddNewArticleActionPerformed
        DialogArticle d = new DialogArticle(this,true);
        d.setVisible(true);
        if(d.isOk()){
            bl.add(d.getArticle());
        }
    }//GEN-LAST:event_jMAddNewArticleActionPerformed

    private void jMRemoveSelectedArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRemoveSelectedArticleActionPerformed
        bl.delete(table.getSelectedRow());
    }//GEN-LAST:event_jMRemoveSelectedArticleActionPerformed

    private void jMSellSelectedArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSellSelectedArticleActionPerformed
       try {
            bl.sellArticles(table.getSelectedRow(),Integer.parseInt(JOptionPane.showInputDialog("Please enter the amount of articles you want to sell")));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMSellSelectedArticleActionPerformed

    private void jMEditSelectedArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEditSelectedArticleActionPerformed
        
    }//GEN-LAST:event_jMEditSelectedArticleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMAddNewArticle;
    private javax.swing.JMenuItem jMBuySelectedJArticle;
    private javax.swing.JMenuItem jMEditSelectedArticle;
    private javax.swing.JMenuItem jMRemoveSelectedArticle;
    private javax.swing.JMenuItem jMSellSelectedArticle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
